int a = 3;
int b = 4;
int c = 7;
int d = 1;
int e = 9;
int max = a;
 if (a > max) max = a;
 if (b > max) max = b;
 if (c > max) max = c;
 if (d > max) max = d;
 if (e > max) max = e;
Console.Write("max = ");
Console.WriteLine(max);
